services:
  db:
    image: postgres:16-alpine
    container_name: granto_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: "PGPASSWORD=postgres pg_isready -h 127.0.0.1 -U docker -d postgres"
